export const INITIALIZE = 'INITIALIZE'
export const SHOW_ERROR_MSG = 'SHOW_ERROR_MSG'

export const SHOW_SNACKBAR = 'SHOW_SNACKBAR'
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR'

export const CHANGE_SIDEBAR = 'CHANGE_SIDEBAR'
